apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: CORS_ORIGIN
              value: "http://localhost:3000"
            - name: USER_SERVICE_URL
              value: "http://user-service:5001"
            - name: DOCTOR_SERVICE_URL
              value: "http://doctor-service:5002"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:5003"
            - name: TELEMEDICINE_SERVICE_URL
              value: "http://telemedicine-service:5005"
            - name: PATIENT_SERVICE_URL
              value: "http://patient-service:8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20