apiVersion: v1
kind: Service
metadata:
  name: symtomeschecker-service
spec:
  selector:
    app: symtomeschecker-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
