apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: NODE_ENV
              value: "production"
            - name: AUTH_MODE
              value: "dev"
            - name: CORS_ORIGIN
              value: "http://localhost:3000"
          readinessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 10
            periodSeconds: 20